// <auto-generated />
namespace MVCKO.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class dbnew1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dbnew1));
        
        string IMigrationMetadata.Id
        {
            get { return "201712171049444_dbnew1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
